name: tanzaku_todo
description: Simple Task manager made for Notion

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.3.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.32.5

dependencies:
  envied: ^0.5.4+1
  firebase_core: ^3.7.1
  firebase_analytics: ^11.3.3
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_web_auth_2: ^4.0.1
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  home_widget: ^0.7.0
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  audioplayers: ^6.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  sentry_flutter: ^8.14.1
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.1
  flutter_native_splash: ^2.4.3
  background_fetch: ^1.3.7
  haptic_feedback: ^0.5.1+1
  wakelock_plus: ^1.2.10
  in_app_review: ^2.0.9
  uni_links: ^0.5.1
  page_transition: ^2.2.1
  purchases_flutter: ^8.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.2
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/
    - assets/google_fonts/
    - assets/sounds/

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon/app_icon.png"
  image_path_ios_dark_transparent: "assets/images/app_icon/app_icon_dark.png"
  image_path_ios_tinted_grayscale: "assets/images/app_icon/app_icon_gray.png"

flutter_native_splash:
  color: "#FAF9F6"
  image: "assets/images/splash/splash_light.png"
  color_dark: "#3D3D3C"
  image_dark: "assets/images/splash/splash_dark.png"
  fullscreen: true

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
