name: tanzaku_todo
description: Simple Task manager made for Notion

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 2.3.2+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  envied: ^1.1.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.0.10+1
  flutter_web_auth_2: ^4.0.1
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^3.0.3
  home_widget: ^0.8.0
  http: ^1.2.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  audioplayers: ^6.1.0
  riverpod_annotation: ^3.0.3
  shared_preferences: ^2.3.2
  table_calendar: ^3.1.2
  sentry_flutter: ^9.9.1
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  package_info_plus: ^9.0.0
  flutter_native_splash: ^2.4.3
  background_fetch: ^1.3.7
  haptic_feedback: ^0.6.4+2
  wakelock_plus: ^1.4.0
  in_app_review: ^2.0.9
  uni_links: ^0.5.1
  page_transition: ^2.2.1
  purchases_flutter: ^9.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  envied_generator: ^1.3.2
  build_runner: ^2.4.0
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  mockito: ^5.6.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true
  assets:
    - assets/images/
    - assets/google_fonts/
    - assets/sounds/

flutter_launcher_icons:
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon/app_icon.png"
  image_path_ios_dark_transparent: "assets/images/app_icon/app_icon_dark.png"
  image_path_ios_tinted_grayscale: "assets/images/app_icon/app_icon_gray.png"

flutter_native_splash:
  color: "#FAF9F6"
  image: "assets/images/splash/splash_light.png"
  color_dark: "#3D3D3C"
  image_dark: "assets/images/splash/splash_dark.png"
  fullscreen: true

flutter_gen:
  output: lib/generated/
  line_length: 80
  integrations:
    flutter_svg: true
